await import('./devops/console.ts')
await import('./envs/dotenv.ts')

queueMicrotask(async function onload() {
	console.log('Deno.env.toObject() ->', Deno.env.toObject())
	// let graylog = await import('./jellyfin/graylog.ts')
	// console.log('graylog.ee.listeners ->', graylog.ee.listeners)
	// await (await import('./workers/jellyfin_worker.ts')).run()
	// console.info('jellyfin ready')
	// await (await import('./workers/nghttpx_worker.ts')).run()
	// console.info('nghttpx ready')
	// await import('./jellyfin/jellyfin.ts')
	// await import('./jellyfin/socket.ts')
	// await import('./jellyfin/search.ts')
})
